/* Volley Coach - planificación semanal */

function lunesDeSemana(d){let x=new Date(d);let day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);x.setHours(0,0,0,0);return x}
function isoDate(d){return d.toISOString().slice(0,10)}
function guardarPlan(){let fecha=$('plan-fecha').value;if(!fecha){alert('Selecciona una fecha.');return}planificacion.push({id:Date.now(),fecha,equipo:EQUIPOS[equipoActivo].nombre,objetivo:$('plan-objetivo').value.trim(),duracion:+$('plan-duracion').value||0,intensidad:$('plan-intensidad').value});save();renderPlanificacion();['plan-objetivo','plan-duracion'].forEach(id=>$(id).value='');$('plan-equipo').value=EQUIPOS[equipoActivo].nombre}
function cambiarSemana(n){semanaBase.setDate(semanaBase.getDate()+n);renderPlanificacion()}
function eliminarPlan(id){planificacion=planificacion.filter(x=>x.id!==id);save();renderPlanificacion()}
function usarPlan(id){let p=planificacion.find(x=>x.id===id);if(!p)return;meta.fecha=p.fecha;meta.equipo=EQUIPOS[equipoActivo].nombre;meta.objetivo=p.objetivo;meta.intensidad=p.intensidad;save();cargarMeta();document.querySelectorAll('.tab-btn')[0].click()}
function renderPlanificacion(){let lunes=lunesDeSemana(semanaBase);let dias=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];$('week-label').textContent=`${lunes.toLocaleDateString('es-ES')} – ${new Date(lunes.getTime()+6*86400000).toLocaleDateString('es-ES')}`;$('week-grid').innerHTML=dias.map((nom,i)=>{let d=new Date(lunes);d.setDate(lunes.getDate()+i);let fecha=isoDate(d),items=planificacion.filter(p=>p.fecha===fecha);return `<div class="day-card"><h4>${nom}<br><span class="small">${d.toLocaleDateString('es-ES',{day:'2-digit',month:'2-digit'})}</span></h4>${items.map(p=>`<div class="plan-item"><b>${esc(p.equipo||'Sesión')}</b><br>${esc(p.objetivo||'Sin objetivo')}<br><span class="small">${p.duracion||0} min · ${esc(p.intensidad)}</span><div class="actions" style="margin-top:6px"><button class="ghost" onclick="usarPlan(${p.id})">Usar</button><button class="danger" onclick="eliminarPlan(${p.id})">×</button></div></div>`).join('')||'<span class="small">Sin sesión</span>'}</div>`}).join('')}
