/* Volley Coach - creación de sesiones y pizarra */

function seccionNaturalEjercicio(e){const fs=normalizarFundamentos(e);if(fs.includes('Control'))return 'controles';const t=(e&&e.tipo)||'';if(t==='Analítico')return 'analiticos';if(t==='Puesta en juego')return 'desarrollo';if(t==='Juego reducido')return 'reducidos';if(t==='Juego')return 'juego';return 'especificos'}
function mapaSeccionesSesion(){if(!meta.seccionesEjercicios||typeof meta.seccionesEjercicios!=='object')meta.seccionesEjercicios={};return meta.seccionesEjercicios}
function mapaNotasBloques(){if(!meta.notasBloques||typeof meta.notasBloques!=='object')meta.notasBloques={};return meta.notasBloques}
function guardarNotaBloque(slug,valor){if(!SECCIONES_ENTRENO[slug])return;mapaNotasBloques()[slug]=valor;save()}
function seccionEjercicioSesion(id,e){return mapaSeccionesSesion()[String(id)]||seccionNaturalEjercicio(e)}
function renderDestinoBiblioteca(){const box=$('session-section-target');if(!box)return;if(!seccionDestinoSesion||!SECCIONES_ENTRENO[seccionDestinoSesion]){box.classList.add('hidden');return}const cfg=SECCIONES_ENTRENO[seccionDestinoSesion];$('session-section-target-name').textContent=cfg.icono+' '+cfg.titulo;if(crearEjercicioDestinoSesion===seccionDestinoSesion){$('session-section-target-note').textContent='Crea el ejercicio. Al guardarlo se añadirá automáticamente a esta sección y volverás al entrenamiento.'}else{$('session-section-target-note').textContent=seccionDestinoSesion==='especificos'?'Puedes elegir cualquier ejercicio; se guardará en Específicos dentro de este entrenamiento.':'El filtro se ha aplicado automáticamente. Los ejercicios que añadas irán a esta sección.'}box.classList.remove('hidden')}
function abrirBibliotecaParaSeccion(slug){const cfg=SECCIONES_ENTRENO[slug];if(!cfg)return;crearEjercicioDestinoSesion=null;seccionDestinoSesion=slug;['buscar','escuela','fundamento','nivel','tipo','favoritos'].forEach(id=>{if($(id))$(id).value=''});if(slug==='especificos'){if($('fundamento'))$('fundamento').value='Todos';if($('tipo'))$('tipo').value='Todos'}else if(cfg.fundamento){if($('fundamento'))$('fundamento').value=cfg.fundamento}else if(cfg.tipo){if($('tipo'))$('tipo').value=cfg.tipo}showView('ejercicios',botonVista('ejercicios'));filtrarEjercicios();renderDestinoBiblioteca();window.scrollTo({top:0,behavior:'smooth'})}
function abrirCrearEjercicioParaSeccion(slug){const cfg=SECCIONES_ENTRENO[slug];if(!cfg)return;cancelarEdicion();seccionDestinoSesion=slug;crearEjercicioDestinoSesion=slug;['buscar','escuela','fundamento','nivel','tipo','favoritos'].forEach(id=>{if($(id))$(id).value=''});setFundamentosSeleccionados([]);if($('nuevo-tipo'))$('nuevo-tipo').value='';if(cfg.fundamento)setFundamentosSeleccionados([cfg.fundamento]);if(cfg.tipo&&$('nuevo-tipo'))$('nuevo-tipo').value=cfg.tipo;$('form-title').textContent='➕ Crear ejercicio para '+cfg.titulo;showView('ejercicios',botonVista('ejercicios'));renderDestinoBiblioteca();filtrarEjercicios();setTimeout(()=>{const el=$('form-title');if(el)el.scrollIntoView({behavior:'smooth',block:'start'})},40)}
function cancelarDestinoSesion(){const estabaCreando=!!crearEjercicioDestinoSesion;seccionDestinoSesion=null;crearEjercicioDestinoSesion=null;if(estabaCreando)cancelarEdicion();renderDestinoBiblioteca();['buscar','escuela','fundamento','nivel','tipo','favoritos'].forEach(id=>{if($(id))$(id).value=''});filtrarEjercicios()}
function volverAlEntrenamiento(){seccionDestinoSesion=null;crearEjercicioDestinoSesion=null;renderDestinoBiblioteca();showView('entrenamiento',botonVista('entrenamiento'));renderizarSesion();window.scrollTo({top:0,behavior:'smooth'})}
function cargarMeta(){['fecha','equipo','jugadores','intensidad','objetivo','notas'].forEach(k=>{let el=$('sesion-'+k);if(el)el.value=meta[k]||''});$('texto-calentamiento').value=meta.calentamiento||'';if(typeof renderSessionRoster==='function')renderSessionRoster();}
function guardarSesionMeta(){meta={...meta,fecha:$('sesion-fecha').value,equipo:EQUIPOS[equipoActivo].nombre,jugadores:$('sesion-jugadores').value,intensidad:$('sesion-intensidad').value,objetivo:$('sesion-objetivo').value,calentamiento:$('texto-calentamiento').value,notas:$('sesion-notas').value};save();renderizarSesion();}
function añadirASesion(id){const e=baseDeDatos.find(x=>x.id===id);if(!e)return;const mapa=mapaSeccionesSesion(),key=String(id),destino=seccionDestinoSesion||seccionNaturalEjercicio(e);if(sesionActual.includes(id)){const actual=seccionEjercicioSesion(id,e);if(seccionDestinoSesion&&actual!==destino){mapa[key]=destino;$('save-indicator').textContent='✓ Movido a '+SECCIONES_ENTRENO[destino].titulo;}else{sesionActual=sesionActual.filter(x=>x!==id);delete mapa[key];$('save-indicator').textContent='✓ Quitado de '+EQUIPOS[equipoActivo].corto;}}else{sesionActual.push(id);mapa[key]=destino;$('save-indicator').textContent='✓ Añadido a '+SECCIONES_ENTRENO[destino].titulo;}meta.seccionesEjercicios=mapa;save();renderizarSesion();filtrarEjercicios();}
function quitarDeSesion(i){const id=sesionActual[i];sesionActual.splice(i,1);if(id!=null)delete mapaSeccionesSesion()[String(id)];save();renderizarSesion();filtrarEjercicios()}
function quitarDeSesionId(id){const i=sesionActual.indexOf(id);if(i>=0)quitarDeSesion(i)}
function moverSesion(i,dir){let j=i+dir;if(j<0||j>=sesionActual.length)return;[sesionActual[i],sesionActual[j]]=[sesionActual[j],sesionActual[i]];save();renderizarSesion();}
function moverSesionEnBloque(id,dir){const e=baseDeDatos.find(x=>x.id===id);if(!e)return;const slug=seccionEjercicioSesion(id,e);const ids=sesionActual.filter(x=>{const ex=baseDeDatos.find(z=>z.id===x);return ex&&seccionEjercicioSesion(x,ex)===slug});const pos=ids.indexOf(id),dest=pos+dir;if(pos<0||dest<0||dest>=ids.length)return;const a=sesionActual.indexOf(ids[pos]),b=sesionActual.indexOf(ids[dest]);[sesionActual[a],sesionActual[b]]=[sesionActual[b],sesionActual[a]];save();renderizarSesion()}
function renderizarSesion(){let total=0;const grupos={controles:[],analiticos:[],especificos:[],desarrollo:[],reducidos:[],juego:[]};sesionActual.forEach(id=>{const e=baseDeDatos.find(x=>x.id===id);if(!e)return;total+=Number(e.tiempo)||0;const slug=seccionEjercicioSesion(id,e);(grupos[slug]||grupos.especificos).push(e)});const orden=['controles','analiticos','especificos','desarrollo','reducidos','juego'];const notas=mapaNotasBloques();let html=orden.map(slug=>{const cfg=SECCIONES_ENTRENO[slug],items=grupos[slug],mins=items.reduce((a,e)=>a+(Number(e.tiempo)||0),0);const body=items.map(e=>{const idx=sesionActual.indexOf(e.id);return `<div class="session-item"><div><b>${idx+1}. ${esc(e.nombre)}</b><div class="small">⏱️ ${e.tiempo||0} min · ${esc(fundamentosTexto(e))} · ${esc(e.intensidad||'Media')}</div><div class="exercise-player-line"><span>👥 ${typeof exercisePlayerSummary==='function'?esc(exercisePlayerSummary(e.id)):'Grupo'}</span><button class="link-btn" onclick="openExercisePlayers(${e.id})">Asignar jugadores</button></div></div><div class="actions"><button class="ghost" onclick="moverSesionEnBloque(${e.id},-1)">↑</button><button class="ghost" onclick="moverSesionEnBloque(${e.id},1)">↓</button><button class="danger" onclick="quitarDeSesionId(${e.id})">Quitar</button></div></div>`}).join('')||`<div class="training-block-empty">${slug==='especificos'?'Elige libremente los ejercicios específicos que quieras.':'Todavía no hay ejercicios en esta sección.'}</div>`;const nota=esc(notas[slug]||'');return `<div class="training-block"><div class="training-block-head"><div class="training-block-title"><span style="font-size:20px">${cfg.icono}</span><div><strong>${esc(cfg.titulo)}</strong><div class="small">${esc(cfg.nota)}${items.length?' · '+mins+' min':''}</div></div><span class="training-block-count">${items.length}</span></div><div class="training-block-actions"><button class="ghost training-block-add" onclick="abrirBibliotecaParaSeccion('${slug}')">＋ Elegir ejercicios</button><button class="primary training-block-create" onclick="abrirCrearEjercicioParaSeccion('${slug}')">＋ Crear ejercicio</button></div></div><div class="training-block-body">${body}<div class="training-block-note-wrap"><label class="training-block-note-label">✍️ Notas / contenido del bloque</label><textarea class="training-block-note" placeholder="Escribe aquí indicaciones, objetivos, progresiones o contenido libre para este bloque..." oninput="guardarNotaBloque('${slug}',this.value)">${nota}</textarea></div></div></div>`}).join('');$('lista-sesion').innerHTML=html;$('tiempo-total').textContent=total+' min';$('num-ejercicios').textContent=sesionActual.length;$('intensidad-resumen').textContent=meta.intensidad||'Media';if(typeof renderSessionRoster==='function')renderSessionRoster();}
function finalizarEntrenamiento(){
  seccionDestinoSesion=null;crearEjercicioDestinoSesion=null;
  const tieneNotasBloques=Object.values(mapaNotasBloques()).some(v=>String(v||'').trim());
  if(!sesionActual.length&&!meta.calentamiento.trim()&&!tieneNotasBloques){alert('La sesión está vacía.');return}
  if(typeof openTrainingClose==='function'){openTrainingClose();return}
  if(confirm('¿Finalizar y guardar esta sesión en el historial?'))confirmarFinalEntrenamiento();
}
function confirmarFinalEntrenamiento(){
  let ejercicios=sesionActual.map(id=>baseDeDatos.find(e=>e.id===id)).filter(Boolean);
  ejercicios.forEach(e=>e.usos=(e.usos||0)+1);
  let duracion=ejercicios.reduce((a,e)=>a+(+e.tiempo||0),0);
  const playerIds=Array.isArray(meta.playerIds)?clonar(meta.playerIds):[];
  const asistencia=typeof trainingCloseData==='function'?trainingCloseData():playerIds.map(playerId=>({playerId,status:'Presente',checkin:'Normal',note:''}));
  historial.unshift({id:Date.now(),...meta,playerIds,asistencia,duracion,pizarra:serializarPizarra(),ejercicios:ejercicios.map(e=>({id:e.id,nombre:e.nombre,tiempo:e.tiempo,tipo:e.tipo||'',seccionSesion:seccionEjercicioSesion(e.id,e),fundamentos:normalizarFundamentos(e),fundamento:normalizarFundamentos(e)[0]||'',descripcion:e.descripcion||'',objetivo:e.objetivo||'',formato:e.formato||'',jugadores:e.jugadores||'',material:e.material||'',variantes:e.variantes||'',errores:e.errores||'',fase:e.fase||'',intensidad:e.intensidad||'',escuela:e.escuela||'',playerIds:typeof exercisePlayerIds==='function'?clonar(exercisePlayerIds(e.id)):clonar(playerIds)}))});
  sesionActual=[];
  meta={fecha:new Date().toISOString().slice(0,10),equipo:EQUIPOS[equipoActivo].nombre,jugadores:'',intensidad:'Media',objetivo:'',calentamiento:'',notas:'',seccionesEjercicios:{},notasBloques:{},playerIds:[],exercisePlayers:{},rosterInitialized:false};
  save();
  if(typeof closeTrainingClose==='function')closeTrainingClose();
  cargarMeta();renderizarSesion();filtrarEjercicios();limpiarPizarra();if(typeof renderPlayers==='function')renderPlayers();
  alert('✅ Entrenamiento guardado. El trabajo individual y la asistencia ya cuentan en Rendimiento.');
}

const canvas=$('pizarra'),ctx=canvas.getContext('2d',{willReadFrequently:true}),wrapper=$('canvas-wrapper');let drawing=false,startX=0,startY=0,currentTool='pencil',currentColor='#1f2937',snapshot=null,undoStack=[];function resizeCanvas(){let old=document.createElement('canvas');old.width=canvas.width;old.height=canvas.height;if(old.width&&old.height)old.getContext('2d').drawImage(canvas,0,0);canvas.width=wrapper.clientWidth;canvas.height=wrapper.clientHeight;if(old.width&&old.height)ctx.drawImage(old,0,0,canvas.width,canvas.height)}window.addEventListener('resize',resizeCanvas);setTimeout(resizeCanvas,50);
function pos(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*(canvas.width/r.width),y:(e.clientY-r.top)*(canvas.height/r.height)}}function pushUndo(){undoStack.push(canvas.toDataURL());if(undoStack.length>20)undoStack.shift()}function restore(url){let im=new Image();im.onload=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(im,0,0,canvas.width,canvas.height)};im.src=url}function setTool(t,b){currentTool=t;document.querySelectorAll('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active')}function setColor(c,b){currentColor=c;document.querySelectorAll('.color-dot').forEach(x=>x.classList.remove('active'));b.classList.add('active')}function startDraw(e){if(e.button!==undefined&&e.button!==0)return;drawing=true;pushUndo();let p=pos(e);startX=p.x;startY=p.y;snapshot=ctx.getImageData(0,0,canvas.width,canvas.height);ctx.beginPath();ctx.moveTo(p.x,p.y)}function draw(e){if(!drawing)return;let p=pos(e);ctx.lineWidth=currentTool==='eraser'?18:4;ctx.lineCap='round';ctx.strokeStyle=currentTool==='eraser'?'#f3b06a':currentColor;if(currentTool==='pencil'||currentTool==='eraser'){ctx.lineTo(p.x,p.y);ctx.stroke();ctx.beginPath();ctx.moveTo(p.x,p.y)}else if(currentTool==='arrow'){ctx.putImageData(snapshot,0,0);ctx.beginPath();ctx.moveTo(startX,startY);ctx.lineTo(p.x,p.y);let a=Math.atan2(p.y-startY,p.x-startX),h=14;ctx.lineTo(p.x-h*Math.cos(a-Math.PI/6),p.y-h*Math.sin(a-Math.PI/6));ctx.moveTo(p.x,p.y);ctx.lineTo(p.x-h*Math.cos(a+Math.PI/6),p.y-h*Math.sin(a+Math.PI/6));ctx.strokeStyle=currentColor;ctx.stroke()}}function endDraw(){drawing=false}canvas.addEventListener('pointerdown',startDraw);canvas.addEventListener('pointermove',draw);canvas.addEventListener('pointerup',endDraw);canvas.addEventListener('pointerleave',endDraw);function deshacer(){let u=undoStack.pop();if(u)restore(u)}function limpiarPizarra(){ctx.clearRect(0,0,canvas.width,canvas.height);$('object-layer').innerHTML='';undoStack=[]}function togglePista(){wrapper.classList.toggle('full');wrapper.classList.toggle('half');resizeCanvas()}function toggleZoneGrid(){const grid=$('zone-grid'),btn=$('zone-toggle');grid.classList.toggle('hidden-grid');btn.classList.toggle('active',!grid.classList.contains('hidden-grid'))}function toggleSubzones(){const grid=$('zone-grid'),btn=$('subzone-toggle');grid.classList.toggle('hide-subzones');btn.classList.toggle('active',!grid.classList.contains('hide-subzones'))}
let playerNum=1;function addObject(type){let el=document.createElement('div');el.className='board-object '+type;if(type==='player')el.textContent=playerNum++>6?playerNum=1:playerNum-1;if(type==='ball')el.textContent='🏐';if(type==='cone')el.textContent='🔺';el.style.left='50%';el.style.top='50%';makeDraggable(el);$('object-layer').appendChild(el)}function addTextObject(){let t=prompt('Texto:');if(!t)return;let el=document.createElement('div');el.className='board-object text';el.textContent=t;el.style.left='50%';el.style.top='50%';makeDraggable(el);$('object-layer').appendChild(el)}function makeDraggable(el){let active=false,ox=0,oy=0;el.onpointerdown=e=>{active=true;let r=wrapper.getBoundingClientRect();ox=e.clientX-r.left-parseFloat(el.style.left)/100*r.width;oy=e.clientY-r.top-parseFloat(el.style.top)/100*r.height;el.setPointerCapture(e.pointerId)};el.onpointermove=e=>{if(!active)return;let r=wrapper.getBoundingClientRect(),x=(e.clientX-r.left-ox)/r.width*100,y=(e.clientY-r.top-oy)/r.height*100;el.style.left=Math.max(0,Math.min(100,x))+'%';el.style.top=Math.max(0,Math.min(100,y))+'%'};el.onpointerup=()=>active=false;el.ondblclick=()=>el.remove()}


function serializarPizarra(){return {canvas:canvas.toDataURL(),pista:wrapper.classList.contains('half')?'half':'full',objetos:[...$('object-layer').children].map(el=>({type:[...el.classList].find(c=>['player','ball','cone','text'].includes(c))||'text',text:el.textContent,left:el.style.left,top:el.style.top}))}}
function aplicarPizarra(data){if(!data)return;wrapper.classList.remove('full','half');wrapper.classList.add(data.pista||'full');$('object-layer').innerHTML='';(data.objetos||[]).forEach(o=>{let el=document.createElement('div');el.className='board-object '+o.type;el.textContent=o.text;el.style.left=o.left;el.style.top=o.top;makeDraggable(el);$('object-layer').appendChild(el)});if(data.canvas)restore(data.canvas)}
function guardarPizarraSesion(){meta.pizarra=serializarPizarra();save();alert('Pizarra de la sesión guardada.')}
function cargarPizarraSesion(){if(meta.pizarra)aplicarPizarra(meta.pizarra);else alert('Esta sesión todavía no tiene una pizarra guardada.')}
function marcarPizarraParaEjercicio(){pizarraParaEjercicio=serializarPizarra();alert('La pizarra actual se asociará al ejercicio al guardarlo.')}
function cargarPizarraEjercicio(id){let e=baseDeDatos.find(x=>x.id===id);if(!e||!e.pizarra)return;aplicarPizarra(e.pizarra);document.querySelectorAll('.tab-btn')[0].click()}
